name: Android Test
on:
  push:
    tags:
      - release.**
      - test.**

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AAB_PATH: build/app/outputs/bundle/release/app-release.aab
      KEYSTORE_PATH: android/upload-keystore.jks
      KEY_PROPS_PATH: android/keystore.properties
      SERVICE_ACCOUNT_PATH: store_credentials.json
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'  # You can change this to match your version
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

#      - name: 📉 Run all app tests
#        run: flutter test

      - name: Decode Android keystore
        run: echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > ${{ env.KEYSTORE_PATH }}

      - name: Decode Android key properties
        run: echo "${{ secrets.KEYSTORE_PROPERTIES }}" | base64 --decode > ${{ env.KEY_PROPS_PATH }}

      - name: Decode Android Service Account
        run: echo "${{ secrets.SERVICE_ACCOUNT_JSON }}" | base64 --decode > ${{ env.SERVICE_ACCOUNT_PATH }}

#      - name: Build
#        run: flutter build apk --release

#      - name: Upload Release APK
#        uses: actions/upload-artifact@v4
#        with:
#          name: release-apk
#          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Build aab
        run: flutter build appbundle --release

      - name: Upload Release AAB
        uses: actions/upload-artifact@v4
        with:
            name: release-aab
            path: ${{ env.AAB_PATH }}

#      - name: Publish to PlayStore
#        uses: r0adkll/upload-google-play@v1
#        with:
#          serviceAccountJson: ${{ env.SERVICE_ACCOUNT_PATH }}
#          packageName: com.cristis.photoeditor.photo_editor
#          releaseFiles: ${{ env.AAB_PATH }}
#          track: internal